# Generated by Django 4.1.3 on 2022-11-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpCategoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_entrada', models.FloatField()),
                ('valor', models.FloatField()),
                ('dataEnt', models.DateField()),
                ('horaEnt', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hist_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_uni', models.FloatField()),
                ('data_alt', models.DateField()),
                ('hora_alt', models.TimeField()),
                ('qtd', models.IntegerField()),
                ('movimentacao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmMarca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('qtd', models.IntegerField()),
                ('valor', models.FloatField()),
                ('tamanho', models.CharField(max_length=2)),
                ('endimg', models.ImageField(upload_to='Produto_img/%Y/%m/%d')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.categoria')),
                ('compra_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.compra_fornecedor')),
                ('hist_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.hist_produto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.marca')),
            ],
        ),
    ]
