# Generated by Django 4.1.2 on 2022-11-30 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_Prod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpCategoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hist_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_uni', models.FloatField()),
                ('data_alt', models.DateField()),
                ('hora_alt', models.TimeField()),
                ('qtd', models.IntegerField()),
                ('movimentacao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmMarca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tamanhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanhos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('qtd', models.IntegerField()),
                ('valor', models.FloatField()),
                ('endimg', models.ImageField(upload_to='Produto_img/%Y/%m/%d')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.categoria')),
                ('hist_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.hist_produto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.marca')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tamanhos')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Hist_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_Prod', models.IntegerField()),
                ('valor_tot', models.FloatField()),
                ('valor_unit', models.FloatField()),
                ('nmProduto', models.CharField(max_length=255)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmFornece', models.CharField(max_length=255)),
                ('qtd_entrada', models.IntegerField()),
                ('valor', models.FloatField()),
                ('dataEnt', models.DateField()),
                ('horaEnt', models.TimeField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.produto')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.produto'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
