# Generated by Django 4.1.2 on 2022-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_carrinho_qtd_prod_hist_produto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_produto',
            name='carrinho',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
