# Generated by Django 4.1.3 on 2022-11-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_carrinho_hist_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_fornecedor',
            name='qtd_entrada',
            field=models.IntegerField(),
        ),
    ]
