# Generated by Django 4.1.3 on 2022-11-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_compra_fornecedor_qtd_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='hist_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.hist_produto'),
        ),
    ]
