# Generated by Django 4.1.2 on 2022-12-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_hist_produto_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='hist_produto',
        ),
        migrations.AddField(
            model_name='hist_produto',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.produto'),
        ),
        migrations.AlterField(
            model_name='hist_produto',
            name='data_alt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hist_produto',
            name='hora_alt',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hist_produto',
            name='movimentacao',
            field=models.CharField(max_length=1),
        ),
    ]
