# Generated by Django 4.1.2 on 2022-12-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_produto_hist_produto_hist_produto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_produto',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.produto'),
            preserve_default=False,
        ),
    ]
