# Generated by Django 4.1.3 on 2022-11-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_produto_hist_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.produto')),
            ],
        ),
    ]
