# Generated by Django 4.1.2 on 2022-12-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_hist_produto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='status',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
