# Generated by Django 4.1.2 on 2022-12-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_carrinho_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
