# Generated by Django 4.1.2 on 2022-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='sac',
            name='status',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
