# Generated by Django 4.1.2 on 2022-12-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_sac_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.ManyToManyField(to='ecommerce.tamanhos'),
        ),
    ]
