# Generated by Django 4.1.2 on 2022-12-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_produto_tamanho_produto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_produto',
            name='tamanho',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
